#%RAML 1.0 DataType

description: Standard error handler response
properties:
  transaction.id:
    description: Unique identifier specific to the message transaction
    type: string
  correlationId:
    description: Unique identifier to group a set of message transactions
    type: string
  timestamp:
    description: Date and time that the error occurred
    type: datetime
  errorDetail:
    description: Details of the error
    type: object
    properties:
      code:
        description: HTTP status code associated with an error
        type: integer
      message:
        description: An error specific message for the end-user
        type: string
      additionalInformation?:
        description: Optional additional information about the error
        type: string