#%RAML 1.0
version: wrong
title: sample-api

/users:
  get:
    description: Search for a user
    queryParameters: 
      first_name:
        description: the first name of the user to search for
        type: number
        required: false
    responses: 
      200:
        description: Users that match the search results
        body: 
          application/json:
      204:
        description: No content
        body: 
          application/json:
  